baseURL = 'https://seolman.github.io'
languageCode = 'en-us'
title = 'github is my second brain'
theme = 'github-style'

[params]
  author = "seolman"
  description = "github is my second brain"
  github = "seolman"
  # linkedin = ""
  email = "tjfehdgns@gmail.com"
  # url = "https://meik2333.com"
  keywords = "blog"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Korea"
  userStatusEmoji = "😀"
  enableGitalk = true
  enableSearch = true
